### ISSUE TITLE
Peer-to-peer code: Bootstrap Version

### ISSUE THREAD

**Issue by RiyaBulia12** [AbigiyaTY/MJ_PT_AB_Portfolio#2]
> While reviewing the code, the following suggestions were made in the meeting:

- We found it helpful that they are using comments for better code understanding :) 
- It would be helpful performance-wise if the bootstrap js bundle is called before the `</body>` closing tag or maybe the link to the js bundle can be removed entirely if the js feature is not being used at all in the project
- We suggested leveraging the bootstrap CSS classes fully (For example, maybe remove the empty `<div>` tag used for centering the element and use the `justify-content-center` class to center the elements on the page )

**Comment by mj-e-boc** [comment]
-Noted, thank you will surely implement the suggestions, they for sure will make the layout better
